"""empty message

Revision ID: 59464b1e55ed
Revises: c53362b5aef1
Create Date: 2024-02-28 19:58:22.345642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59464b1e55ed'
down_revision = 'c53362b5aef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppies', schema=None) as batch_op:
        batch_op.drop_column('breed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
